function importfile2(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 22-May-2022 10:36:30

% Import the file
A=fileToRead1;
newData1 = load('-mat', fileToRead1);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    if strcmp(A,'aerosoles_seco')|strcmp(A,'humedad')    
        assignin('base',string(A) , newData1.(vars{i}));
    else
        assignin('base',string(A) , newData1.(vars{i}));
    end
end
